### ISSUE TITLE
rockspecs

### ISSUE THREAD

**Issue by catwell** [Etiene/valua#6]
There is a valua 0.2.2 on LuaRocks but the rockspec is not in the GitHub repository and it does not support 5.3. There is a valua-0.2.1-2 rockspec that supports 5.3 in the repository but it is invalid (the version in the file is wrong) and it is not in LuaRocks.

**Comment by catwell** [comment]
:+1: :party:

**Comment by Etiene** [comment]
Sorry for the delay, I only saw this today! xD
